spring.application.name=ai-analyzer-service
server.port=8081
gemini.api.key=AIzaSyDx15GruN45l_-WT0MBK6o162A4C6Ikq7s
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/runbook_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:runbook_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:runbook_password}

# Hibernate JPA Settings (Auto-create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect